spring:
  session:
    store-type: redis
  http:
    encoding:
      charset: utf-8
      enabled: true
      force: true
  redis:
    database: 0
    host: localhost
    poll:
      max-active: 8
      max-wait: 1
      max-idle: 0
      min-idle: 0
      timeout: 300

server:
  port: 10400